// encode_credentials.js
const fs = require('fs');

// Read the credentials file
const credentialsPath = './my-project-92814-457204-55b9d43a15b3.json';
const credentials = fs.readFileSync(credentialsPath, 'utf8');

// Convert to Base64
const base64Credentials = Buffer.from(credentials).toString('base64');

// Output the Base64 string
console.log('Your Base64 encoded credentials:');
console.log(base64Credentials);
console.log('\nCopy this string and add it to your Render environment variables as GOOGLE_CLOUD_CREDENTIALS_BASE64');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add it as an environment variable in Render:');
console.log('GOOGLE_CLOUD_CREDENTIALS_BASE64=<the-base64-string>');
console.log('\nCopy the above string and add